kernel:
  image: linuxkit/kernel:5.4.28
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 isolcpus=nohz,domain,2 nohz_full=2 rcu_nocbs=2 rcu_nocb_poll intel_pstate=disable nosoftlockup=0 cpuidle.off=1 intel_idle.max_cstate=0 processor.max_cstate=0"
init:
  - linuxkit/init:a0246dd478a24abbee0a4cede99662ffc4931691
  - linuxkit/runc:69b4a35eaa22eba4990ee52cccc8f48f6c08ed03
  - linuxkit/containerd:09553963ed9da626c25cf8acdf6d62ec37645412

onboot:
  - name: bmtune
    image: ssungam/bmtune:latest
    ipc: host
    pid: host
    capabilities:
            - all
    command: ["/bmtune"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]

services:
  - name: rngd
    image: linuxkit/rngd:02c555b50cd1887aa628836662d2eec54c0d7e81
  - name: sshd
    image: linuxkit/sshd:v0.7
  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    runtime:
     mounts:
       - type: overlay
         source: overlay
         destination: writeable-var-lib-docker
         options: ["rw", "lowerdir=/docker-data", "upperdir=/run/hostdocker/upper", "workdir=/run/hostdocker/work"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]

files:
  - path: /docker-data
    directory: true
  - path: etc/docker/daemon.json
    contents: |
        {"debug": true,
         "data-root": "/docker-data",
         "hosts": [
                "tcp://0.0.0.0:2375"
         ]
        }
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true

trust:
  org:
    - linuxkit
